### ISSUE TITLE
在庫システムに追加したい機能

### ISSUE THREAD

**Issue by natsu-cat** [2D-4/system-development#1]
ここに資料に書いてある販売在庫システム(夏季休暇前に貰った奴です。)を見て、追加したい機能、○○のプロセスを○○に変更したいなどの意見を書いてください。

みんなの意見を全員で見ながら、共感したり、良かったりしたところを話し合って決めたいので、小さいことでも、思ったことでもなんでも構わないです。

9月24日の初回授業に、システムの要求分析、システムの規模、どのような機能があるかなど作成するシステムをイメージできる内容をレポートにまとめ、スケジュールを立てないといけないので、なるべく早めにお願いします。

**Comment by n-shogo** [comment]
、

**Comment by Flasushi** [comment]
**商品は美容用品から本に変更**

**中野くん**

- お知らせ機能　（発注、発注実績）

**上柴くん**

- ログイン機能（バーコードを用いる）

**中本くん**

- 商品が一定数足りなくなった場合、表示して教えてくれる機能

**與那城くん**

- ポイント機能（階級制）
