### ISSUE TITLE
画面仕様書の作成

### ISSUE THREAD

**Issue by natsu-cat** [2D-4/system-development#42]
featureブランチを切り、画面仕様書の内部設計部分を作成する。作成後、PRし、レビュー後developブランチにマージされる。
※フォントはメイリオにする。
その他の設定はリーダーにきく(暫定では手をつけなくて良い)

**Comment by messcat-38** [comment]
パスワード変更画面について
現在、社員IDと現在使用中のパスワードを入力してから、パスワード変更画面に移行する画面設計になっていますが正直言って冗長な気がするので、
・社員ID
・現在使用中のパスワード
・新規パスワード
・新規パスワード(誤字防止で2回入力する)
を一つの画面に収めたらスマートかなと思うんですがいかがですか？

**Comment by n-shogo** [comment]
パスワード変更画面についての件、確認しました。
確かに今の状態では冗長な気がしますので、一つの画面に収めたいと思います。
作業の方は荒木くんに任せます。

**Comment by n-shogo** [comment]
発注内容最終確認画面、登録完了画面、注文内容最終確認画面、変更完了画面について
先週、上柴くんが指摘していたのですが、上記の画面をフォームではなくMessageBoxにするという案が出たのですが、どうでしょうか？

**Comment by n-shogo** [comment]
新しいフォームの入出庫詳細画面について
今のままでは、発注詳細、注文詳細を見ることが難しく、出庫済みや入庫済みなどの処理もあやふやな為、それらの機能を持った新しいフォームを追加したいなと思っています。

手順としては、

- ビューに表示されている発注ID・注文IDをダブルクリックすることで開くフォームを予定しています。

- また、この画面で入出庫処理もできるようにしたいです。

- もしトラブルが起こった場合、「入出庫処理した発注ID・注文IDを未入庫・未出庫に戻したい時」など、同じようにフォームを開くことで、未入庫・未出庫状態にすることが出来るフォームにする予定です。

作業の方は中本くん @nakamotoD に任せています。
